id = "eevr"
version = "1.1.0"
name = "eeVR"
tagline = "Render in different projections using Eevee engine"
maintainer = "EternalTrail <https://github.com/EternalTrail/eeVR>"
type = "add-on"
website = "https://github.com/EternalTrail/eeVR"
tracker_url = "https://github.com/EternalTrail/eeVR/issues"
permissions = ["FILES"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
copyright = ["2023-2025 EternalTrail"]
category = "render"
tags = ["panorama", "360", "vr", "eevee"]
